### ISSUE TITLE
Errno 111: Connection Refused

### ISSUE THREAD

**Issue by Pika-Boo** [chrismattmann/tika-python#134] opened 2017-03-26 16:20 UTC
Getting the following error while trying to use the parser:
![image](https://cloud.githubusercontent.com/assets/7687847/24333003/3d4f12d4-126e-11e7-9d8b-ca0bd7f5cc23.png)

**Comment by chrismattmann** [comment] 2017-03-26 17:42
Hey @Pika-Boo can you make sure that you don't have any running instances of programs on 9998 (including prior Tika servers). First try `killall java` then try starting python and importing tika and running it.

**Comment by mitschwimmer** [comment] 2017-04-12 11:47
Hey @chrismattmann, first of all, thanks for this very handy tool.

I just wanted to let you know  that I had the same error message as pika-boo. The reason for me was quite trivial -I did not have java installed on the machine. Once I installed JRE everything works as expected and known from my dev machine.

**Comment by chrismattmann** [comment] 2017-04-25 17:25
thank you @mitschwimmer appreciate the feedback. I'm going to close this assuming this is the root cause. Please re-open @Pika-Boo if that was not the issue.

**Closed by chrismattmann** 2017-04-25 17:25 UTC
Labels: bug, question

**Comment by cymox1** [comment] 2018-05-10 10:42
I was having this issue `openjdk version "10.0.1" ` (openjdk-11-jre? which as default-jre on Ubuntu 18.04), it was resolved after reverting to openjdk-8-jre.

If you look at /tmp/tika-server.log, you should be able to find the root cause, in my case it was an issue similar to [this](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j)

**Comment by chrismattmann** [comment] 2018-05-15 04:31
Tika doesn't work with anything newer than JDK8 I believe...
