### ISSUE TITLE
Failed to establish a new connection: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by fysteven** [chrismattmann/tika-python#98] opened 2016-04-19 20:33 UTC
Tried using Tika-Python earlier today. Got the following error. Seems to be exceeding some maximum connections.

It also seems to be a problem with Tika Server.

Traceback (most recent call last):
  File "yao_file_detector.py", line 40, in <module>
    main()
  File "yao_file_detector.py", line 36, in main
    detect_files('/Users/Frank/working-directory/fulldump/file-type.txt')
  File "yao_file_detector.py", line 23, in detect_files
    file_type = detector.from_file(''.join([base_directory, val]))
  File "/Library/Python/2.7/site-packages/tika/detector.py", line 22, in from_file
    jsonOutput = detectType1('type', filename)
  File "/Library/Python/2.7/site-packages/tika/tika.py", line 223, in detectType1
    verbose, tikaServerJar)
  File "/Library/Python/2.7/site-packages/tika/tika.py", line 256, in callServer
    resp = verbFn(serviceUrl, encodedData, headers=headers)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 120, in put
    return request('put', url, data=data, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9998): Max retries exceeded with url: /detect/stream (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x118ec4590>: Failed to establish a new connection: [Errno 61] Connection refused',))

**Comment by chrismattmann** [comment] 2016-04-19 20:47
Hi Frank @fysteven were you doing lots of parallel connections?

**Comment by fysteven** [comment] 2016-04-19 20:55
Hi Chris @chrismattmann , the following snippet is how I iterated the file list.
It failed around the 8181st detection of file.
Looks like the Tika Server would establish a new connection for each detection, right?

```
        for idx, val in enumerate(file_list):
            file_name = os.path.basename(val)
            file_type = detector.from_file(''.join([base_directory, val]))
```

**Comment by chrismattmann** [comment] 2016-04-22 23:34
hi @fysteven any update here? Are you still seeing this?

**Comment by chrismattmann** [comment] 2016-05-17 04:36
closing since I never heard back. Please re-open if you still see this.

**Closed by chrismattmann** 2016-05-17 04:36 UTC
Labels: bug, help wanted

**Comment by bainadeashish** [comment] 2016-08-26 12:43
I am getting text contents from Azure web server with below code
from tika import parser
text = parser.from_file(file)--file is doc file

I am getting below error
HTTPConnectionPool(host='localhost', port=9998): Max retries exceeded with url: /rmeta/text (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions',))

**Comment by mahtani89** [comment] 2018-02-22 13:21
Has anyone found a fix to the issue?

**Comment by chrismattmann** [comment] 2018-02-26 02:12
The issue usually relates to:

1. Your firewall doesn't allow incoming connections on localhost to 9998
2. You already had your own Tika server running on 9998 (not started by Python) and something gets messed up - you need to kill that Tika server, and then let Python start it for you.
