### ISSUE TITLE
extracting text out of archive files

### ISSUE THREAD

**Issue by lathakris** [chrismattmann/tika-python#190] opened 2018-07-26 23:20 UTC
Hi,

Just a question on the archive files text extraction, the unpack interface does not extract text out of archive files ? Is this expected ? (unpack.from_file() does not extract text from archive files only parser.from_file() does)

Thank you.

**Comment by chrismattmann** [comment] 2018-08-09 15:40
duplicate of https://github.com/chrismattmann/tika-python/issues/172

**Closed by chrismattmann** 2018-08-09 15:40 UTC
Labels: duplicate
