### ISSUE TITLE
Multiple extra \n at the beginning of the output text

### ISSUE THREAD

**Issue by ololobus** [chrismattmann/tika-python#112] opened 2016-06-17 20:16 UTC
I have a running Tika server locally at `http://localhost:9998/tika`

When I use it directly via curl it returns proper result:

``` shell
|--> curl -T EnglishSample\ \(dragged\).pdf http://localhost:9998/tika
3TOEIC Speaking and Writing Sample Tests

The TOEIC Speaking and Writing Tests
The TOEIC Speaking and Writing tests include tasks that people might perform in work-related 
situations or in familiar daily activities that are common across cultures. The tests assess English-
language speaking and writing profi ciency and do not require test takers to have specialized 
knowledge of business. 
```

But using `tika-python` I get extra `\n`'s:

``` python
In [9]: parser.from_file('EnglishSample (dragged).pdf', 'http://localhost:9998/tika')['content']
Out[9]: u'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nuntitled\n\n\n3TOEIC Speaking and Writing Sample Tests\n\nThe TOEIC Speaking and Writing Tests\nThe TOEIC Speaking and Writing tests include tasks that people might perform in work-related \nsituations or in familiar daily activities that are common across cultures. ...
```

Looks like a problem with `tika-python` package or it uses additional params with Tika which can be changed?
Please, find pdf attached. [EnglishSample (dragged).pdf](https://github.com/chrismattmann/tika-python/files/321223/EnglishSample.dragged.pdf)

**Comment by chrismattmann** [comment] 2016-06-23 22:46
Hi @ololobus do you have any idea why this is happening? I've looked and it's non obvious to me, perhaps something in parser.from_file?

**Comment by ololobus** [comment] 2016-06-26 17:52
Hi @chrismattmann I have no clear ideas too, but I would rather look deeper into call stack, e.g. https://github.com/chrismattmann/tika-python/blob/master/tika/tika.py#L313. Maybe some multiple decoding/encoding error.

I use latest Tika server and noticed, that result sometimes differs when using different server endpoints: `/tika` (no multipart, entire file inside message body) and `/tika/form` (supports multipart). But here everywhere used `/tika`.

I'll see more later

**Comment by chrismattmann** [comment] 2016-06-26 20:31
hey @ololobus do you think it's: https://github.com/chrismattmann/tika-python/blob/master/tika/parser.py#L50 - in particular on that line, I take multiple JSONs (in case it's a composite type), and then aggregate together the parsed content and the parsed metadata. If the parsed content is '\n\n' I could see it getting replicated for a few times over.

**Comment by chrismattmann** [comment] 2017-02-28 15:30
hmm, I'm going to close this as Wont Fix for now. I could strip out the newlines and I think [Line 50](https://github.com/chrismattmann/tika-python/blob/master/tika/parser.py#L50) is where the issue is coming from but this is a harder problem than first thought. How do I know how many \n to strip at the end? It seems like it only affects files that have multiple JSON that are output too.

**Closed by chrismattmann** 2017-02-28 15:30 UTC
Labels: bug, help wanted
