### ISSUE TITLE
Encoding filename as utf-8 leads to UnicodeEncodeError when filename is in Chinese

### ISSUE THREAD

**Issue by Hausekey** [chrismattmann/tika-python#225] opened 2019-04-15 00:21 UTC
Hi there,

Thought it may help to re-open #167 to save some time for anyone else with a similar problem.
After spending some time debugging, I came to the same conclusion as #222. 

My issue:
```
import tika
tika.initVM()
from tika import parser

parsed = parser.from_file('做好水煮牛3重點風味直逼大飯店.pdf'.encode('utf-8'))
print(parsed["metadata"])
print(parsed["content"])
```

Stacktrace:
```
Traceback (most recent call last):
  File "C:/Users/Jackie/PycharmProjects/parsepdf/parse_pdf.py", line 6, in <module>
    parsed = parser.from_file('做好水煮牛3重點風味直逼大飯店.pdf'.encode('utf-8'))
  File "C:\Users\Jackie\PycharmProjects\parsepdf\venv\lib\site-packages\tika\parser.py", line 36, in from_file
    jsonOutput = parse1('all', filename, serverEndpoint, headers=headers, config_path=config_path)
  File "C:\Users\Jackie\PycharmProjects\parsepdf\venv\lib\site-packages\tika\tika.py", line 320, in parse1
    path, file_type = getRemoteFile(urlOrPath, TikaFilesPath)
  File "C:\Users\Jackie\PycharmProjects\parsepdf\venv\lib\site-packages\tika\tika.py", line 680, in getRemoteFile
    urlp = urlparse(urlOrPath)
  File "C:\Users\Jackie\AppData\Local\Programs\Python\Python37\lib\urllib\parse.py", line 367, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "C:\Users\Jackie\AppData\Local\Programs\Python\Python37\lib\urllib\parse.py", line 123, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "C:\Users\Jackie\AppData\Local\Programs\Python\Python37\lib\urllib\parse.py", line 107, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "C:\Users\Jackie\AppData\Local\Programs\Python\Python37\lib\urllib\parse.py", line 107, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
```

What fixed it:
In tika.py line 321, changing 
`    headers.update({'Accept': responseMimeType, 'Content-Disposition': make_content_disposition_header(path)})
`
to
`    headers.update({'Accept': responseMimeType, 'Content-Disposition': make_content_disposition_header(path.encode('utf-8') if type(path) is unicode_string else path)})`

In my own file, reverting
`parsed = parser.from_file('做好水煮牛3重點風味直逼大飯店.pdf'.encode('utf-8'))
`
back to
`parsed = parser.from_file('做好水煮牛3重點風味直逼大飯店.pdf')
`

**Comment by chrismattmann** [comment] 2019-05-31 18:01
fixed in #222

**Closed by chrismattmann** 2019-05-31 18:01 UTC
Labels: bug, enhancement

**Comment by rblock-aw** [comment] 2019-09-09 12:28
Hi Chris,

We are currently experiencing the same issue. From what I read, I gather that the issue is indeed fixed in the code, but that it is scheduled to release with version 2.0.0, which is not completed yet. Is it possible to do a bug fix release in the meantime (pretty please)? Anyways, thank you for your hard work and your awesome project!

**Comment by chrismattmann** [comment] 2019-11-09 16:00
thanks @rblock-aw are you still experiencing this even after #222?

**Comment by rblock-aw** [comment] 2019-11-13 10:49
We'll look into it, I'll keep you posted.

**Comment by cneben** [comment] 2019-11-14 17:28
Unfortunately, 1.22 does not seems to fix the bug.

The problem is in tika.py: in function getRemoteFile, the urlparse() call does not works with non-ascii charcaters. Encoding the url given to parser.from_file() works (ie parser.from_file(urllib.parse.quote(str))), but then the call open() in parse1() fails because there is no url decoding for local files...

The best way of fixing this would be to force a properly encode  'file:///' as an argument with decoding before open (or even better by using urllib.request.urlopen()).  

Thanks for your work !
